name: Feature testing
on: [push, pull_request, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          node-version: '20.x'
    - name: Installing dependencies.
      run: npm i
    - name: Installing TS-Node
      run: npm install -g ts-node
    - name: Channel Features
      run: ts-node ./scripts/tests/channel.ts
      env:
        TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
    - name: Message Features
      run: ts-node ./scripts/tests/message.ts
      env:
        TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
