name: Publish Release
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  lint:
    name: ESLint
    uses: ./.github/workflows/lint.yml

  publish:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
